# Generated by Django 5.0 on 2023-12-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0004_cellphoneaccesstoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellphoneSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("whatsapp", models.CharField(max_length=255, verbose_name="Whatsapp")),
                ("suggestion", models.TextField(verbose_name="Sugestão")),
            ],
            options={
                "verbose_name": "Sugestão",
                "verbose_name_plural": "Sugestões",
            },
        ),
    ]
