# Generated by Django 5.0 on 2023-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0007_alter_cellphone_news_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphone",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="É principal?"),
        ),
        migrations.AlterField(
            model_name="cellphonewriter",
            name="input",
            field=models.TextField(
                help_text="\nSiga rigorosamente este formato: <br>\n<br>\nATUALIZAR:\n\n<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\n\n<br>\n\nADICIONAR:\n\n<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\n\n<br>\n\nREMOVER:\n\n<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\n\n<br>\n            ",
                verbose_name="Entrada",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cellphone",
            unique_together={("brand", "model")},
        ),
    ]
