# Generated by Django 5.0 on 2023-12-15 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0008_cellphone_is_main_alter_cellphonewriter_input_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphone",
            name="scheduled_to",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Agendado para",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cellphonewriter",
            name="input",
            field=models.TextField(
                help_text='\nSiga rigorosamente este formato: <br>\n<br>\nATUALIZAR:\n\n<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\n\n<br>\n\nADICIONAR:\n\n<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3<br>\n\n<br>\n\nREMOVER:\n\n<br>\nMarca Modelo<br>\nMarca Modelo<br>\n\n<br>\n\n<hr class="solid">\n\nOpcionalmente, você pode colocar no final de cada linha de ação, uma data que queira que seja publicada aquele celular, Exemplo: <br>\n\n<br>\n\nMarca Modelo: Marca Modelo 1 - Marca Modelo 2 - Marca Modelo 3 [d/m/YYYY]<br>\n            ',
                verbose_name="Entrada",
            ),
        ),
    ]
