# Generated by Django 5.0 on 2023-12-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0010_alter_cellphone_scheduled_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
    ]
