# Generated by Django 5.0 on 2023-12-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0011_brand_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Ordem"
            ),
        ),
    ]
