# Generated by Django 5.0 on 2023-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0012_alter_brand_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellphone",
            name="cellphone_screen_protector_compatibilities",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                to="cellphone.cellphone",
                verbose_name="Compatibilidades com películas",
            ),
        ),
    ]
