# Generated by Django 5.0 on 2023-12-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0015_alter_cellphoneaccess_days_to_expire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cellphone",
            name="cellphone_screen_protector_compatibilities",
        ),
        migrations.RemoveField(
            model_name="cellphone",
            name="is_main",
        ),
        migrations.AddField(
            model_name="cellphone",
            name="compatibility_line",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Linha de compatibilidade",
            ),
        ),
        migrations.AddField(
            model_name="cellphone",
            name="is_visible_for_test",
            field=models.BooleanField(
                default=False, verbose_name="É visível para testes?"
            ),
        ),
    ]
