# Generated by Django 5.0 on 2023-12-19 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cellphone",
            "0016_remove_cellphone_cellphone_screen_protector_compatibilities_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cellphone",
            unique_together=set(),
        ),
    ]
