# Generated by Django 5.0 on 2023-12-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0017_alter_cellphone_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphoneaccess",
            name="is_test_access",
            field=models.BooleanField(default=True, verbose_name="É acesso de teste?"),
        ),
    ]
