# Generated by Django 5.0 on 2023-12-19 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0018_cellphoneaccess_is_test_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellphoneAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip", models.CharField(max_length=255, verbose_name="IP")),
                ("user_agent", models.TextField(verbose_name="User agent")),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="cellphone.cellphoneaccess",
                        verbose_name="Acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de acesso",
                "verbose_name_plural": "Logs de acesso",
            },
        ),
    ]
