# Generated by Django 5.0 on 2023-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0020_cellphoneaccesstry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphoneaccess",
            name="access_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="\nLimite de acessos atrelados aos IPs. <br>\nAbaixo você consegue ver todos os IPs usados para este cadastro. <br>\n            ",
                verbose_name="Limite de acessos",
            ),
        ),
    ]
