# Generated by Django 5.0 on 2023-12-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0022_alter_cellphoneaccess_is_test_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellphoneaccess",
            name="days_to_expire",
            field=models.CharField(
                choices=[
                    ("3", "3 dias"),
                    ("30", "30 dias"),
                    ("90", "90 dias"),
                    ("180", "180 dias"),
                ],
                default="30",
                max_length=255,
                verbose_name="Dias para expirar",
            ),
        ),
    ]
