# Generated by Django 5.0 on 2024-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0024_alter_cellphonewriter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphoneaccess",
            name="is_plus_access",
            field=models.BooleanField(default=True, verbose_name="Visão Completa"),
        ),
    ]
