# Generated by Django 5.0 on 2024-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellphone", "0025_cellphoneaccess_is_plus_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellphoneaccess",
            name="was_converted",
            field=models.BooleanField(default=False, verbose_name="Virou acesso PLUS?"),
        ),
        migrations.AlterField(
            model_name="cellphoneaccess",
            name="is_plus_access",
            field=models.BooleanField(default=True, verbose_name="Versão Completa"),
        ),
    ]
