# Generated by Django 5.0 on 2024-01-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CellphoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Modelo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.CreateModel(
            name="CellphoneModelLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "screen_protectors",
                    models.PositiveIntegerField(verbose_name="Películas"),
                ),
                ("cases", models.PositiveIntegerField(verbose_name="Capinhas")),
                (
                    "cellphone_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_line",
                        to="orderlist.cellphonemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Modelo",
                "verbose_name_plural": "Linhas de Modelo",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("whatsapp", models.CharField(max_length=255, verbose_name="Whatsapp")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Mensagem"),
                ),
                (
                    "cellphone_models",
                    models.ManyToManyField(
                        related_name="orders",
                        to="orderlist.cellphonemodelline",
                        verbose_name="Modelos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
    ]
