# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Delivery to Production

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  DB_HOST: ${{ secrets.POSTGRES_HOST }}
  DB_PORT: ${{ secrets.POSTGRES_PORT }}

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ENVIRONMENT: prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Zappa Deploy to Production
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Building Environment
      run: |
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
        echo DB_HOST=${{ secrets.POSTGRES_HOST }} >> .env
        echo DB_PORT=${{ secrets.POSTGRES_PORT }} >> .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
        echo ENVIRONMENT=prod >> .env

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure AWS
      run: |
        source venv/bin/activate
        aws configure set region us-east-1
        aws configure set output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploying
      run: |
        source venv/bin/activate
        zappa update dev

    - name: Migrating the database
      run: |
        source venv/bin/activate
        zappa manage dev migrate
